version: 2
updates:
  # Root package.json
  - package-ecosystem: "npm"
    directory: "./"
    schedule:
      interval: "daily"
    open-pull-requests-limit: 20
    commit-message:
      prefix: "chore(deps):"
